CREATE TABLE IF NOT EXISTS mpa_rating (
  mpa_rating_id INT PRIMARY KEY,
  name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id INT PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS films (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(200),
  release_date DATE,
  duration INT,
  mpa_rating_id INT,
  FOREIGN KEY (mpa_rating_id) REFERENCES mpa_rating(mpa_rating_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
  film_id BIGINT,
  genre_id INT,
  PRIMARY KEY (film_id, genre_id),
  FOREIGN KEY (film_id) REFERENCES films(id),
  FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) NOT NULL,
  login VARCHAR(100) NOT NULL,
  birthday DATE
);

CREATE TABLE IF NOT EXISTS film_like (
  user_id BIGINT,
  film_id BIGINT,
  PRIMARY KEY (user_id, film_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (film_id) REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS user_friend (
  user_id BIGINT,
  friend_id BIGINT,
  PRIMARY KEY (user_id, friend_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (friend_id) REFERENCES users(id)
);
